geoevents/director/urls.py
# This technical data was produced for the U. S. Government under Contract No. W15P7T-13-C-F600, and
# is subject to the Rights in Technical Data-Noncommercial Items clause at DFARS 252.227-7013 (FEB 2012)

from django.conf.urls import patterns, include, url
from django.contrib.auth.decorators import permission_required
from django.core.urlresolvers import reverse_lazy
from django.views.generic.edit import DeleteView, UpdateView

from .views import *
from .models import Report

urlpatterns = patterns('',
                       url(r'^$', DirectorDashboardViewList.as_view(), name='director-dashboards'),
                       url(r'^board/$', DirectorDashboardViewList.as_view(), name='director-dashboards'),
                       url(r'^board/(?P<pk>\d+)/$', 'geoevents.director.views.DirectorDashboardView',
                           name='director-dashboard-view'),
                       url(r'^board/(?P<pk>\d+)/(?P<slug>[\w\d\-]+)/$',
                           'geoevents.director.views.DirectorDashboardView', name='director-dashboard-view-slug'),
                       url(r'^board/(?P<org>\w+)/$', 'geoevents.director.views.DirectorDashboardViewOrg',
                           name='director-dashboard-view-org'),

                       url(r'^rate/(?P<model>\w+)/(?P<pk>\d+)/$', 'geoevents.director.views.SocialRate',
                           name='social-rate'),

                       url(r'^quadchart/(?P<pk>\d+)/$', 'geoevents.director.views.QuadChartView',
                           name='prog-obs-quad-chart'),

                       url(r'^note/new/$', 'geoevents.director.views.NoteNew', name='notes-submit-new'),
                       url(r'^report/new/$', 'geoevents.director.views.ReportNew', name='reports-submit-new'),

                       url(r'^report/link/(?P<pk_report>\d+)/(?P<model>\w+)/(?P<pk_target>\d+)/$',
                           'geoevents.director.views.ReportLink', name='reports-linkage'),
                       url(r'^report/$', ListView.as_view(queryset=Report.objects.filter(public=1),
                                                          template_name='report-list.html',
                                                          paginate_by=25,
                       ), name='reports-view-reports'),
                       url(r'^report/(?P<pk>\d+)/$', DetailView.as_view(queryset=Report.objects.all(),
                                                                        template_name='report.html',
                       ), name='reports-view-report'),
                       url(r'^report/add/$', permission_required('director.add_report', reverse_lazy('home'))(
                           ReportCreateView.as_view(template_name='report-manage.html',
                                                    success_url=reverse_lazy('reports-view-reports'),
                           )), name='reports-manage-report'),
                       url(r'^report/manage/(?P<pk>\d+)/$',
                           permission_required('director.change_report', reverse_lazy('home'))(
                               UpdateView.as_view(queryset=Report.objects.all(),
                                                  form_class=ReportForm,
                                                  template_name='report-manage.html',
                               )), name='reports-manage-report-id'),
                       url(r'^report/delete/(?P<pk>\d+)/$',
                           permission_required('director.delete_report', reverse_lazy('home'))(
                               DeleteView.as_view(model=Report,
                                                  template_name='generic-delete.html',
                                                  success_url=reverse_lazy('reports-view-reports'))
                           ), name='reports-delete-report-id'),


                       url(r'^action/(?P<pk>\d+)/$', DetailView.as_view(queryset=Actions.objects.all(),
                                                                        template_name='report.html',
                       ), name='actions-view-report'),
                       url(r'^action/new/$', 'geoevents.director.views.ActionNew', name='actions-submit-new'),
                       url(r'^action/add/(?P<success_url>.*)$',
                           ActionCreateView.as_view(template_name='report-manage.html', ),
                           name='actions-manage-report-return'),
                       url(r'^action/add/$', permission_required('director.add_actions', reverse_lazy('home'))(
                           ActionCreateView.as_view(template_name='report-manage.html',
                                                    success_url=reverse_lazy('actions-view-reports'),
                           )), name='actions-manage-report'),
                       url(r'^action/manage/(?P<pk>\d+)/$',
                           permission_required('director.change_actions', reverse_lazy('home'))(
                               UpdateView.as_view(queryset=Actions.objects.all(),
                                                  form_class=ActionForm,
                                                  template_name='report-manage.html',
                               )), name='actions-manage-report-id'),

                       url(r'^action/delete/(?P<pk>\d+)/$',
                           permission_required('director.delete_actions', reverse_lazy('home'))(
                               DeleteView.as_view(model=Report,
                                                  template_name='generic-delete.html',
                                                  success_url=reverse_lazy('actions-view-reports'))
                           ), name='actions-delete-report-id'),

                       url(r'^billet/(?P<pk>\d+)/$', DetailView.as_view(queryset=Billet.objects.all(),
                                                                        template_name='report.html',
                       ), name='billets-view-report'),
                       ##    url(r'^billet/new/$', 'geoevents.director.views.BilletNew', name='billets-submit-new'),
                       url(r'^billet/add/$', permission_required('director.add_billet', reverse_lazy('home'))(
                           BilletCreateView.as_view(template_name='report-manage.html',
                                                    success_url=reverse_lazy('billets-view-reports'),
                           )), name='billets-manage-report'),
                       url(r'^billet/manage/(?P<pk>\d+)/$',
                           permission_required('director.change_billet', reverse_lazy('home'))(
                               UpdateView.as_view(queryset=Billet.objects.all(),
                                                  form_class=BilletForm,
                                                  template_name='report-manage.html',
                               )), name='billets-manage-report-id'),
                       url(r'^billet/delete/(?P<pk>\d+)/$',
                           permission_required('director.delete_billet', reverse_lazy('home'))(
                               DeleteView.as_view(model=Report,
                                                  template_name='generic-delete.html',
                                                  success_url=reverse_lazy('billets-view-reports'))
                           ), name='billets-delete-report-id'),


)

geoevents/urls.py
# This technical data was produced for the U. S. Government under Contract No. W15P7T-13-C-F600, and
# is subject to the Rights in Technical Data-Noncommercial Items clause at DFARS 252.227-7013 (FEB 2012)

from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.core.urlresolvers import reverse_lazy
from django.views.generic import RedirectView
from geoevents.views import UserPermsUpdate
from geoevents.core.api import UserResource
from geoevents.maps.api import LayerResource, MapResource, MapLayerResource
from geoevents.operations.api import EventResource, EventTypesResource, LessonLearnedResource
from geoevents.timeline.api import TimelineItemResource
from geoevents.views import UserPermsUpdate
from tastypie.api import Api

admin.autodiscover()

v1_api = Api(api_name='v1')
v1_api.register(EventResource())
v1_api.register(LessonLearnedResource())
v1_api.register(LayerResource())
v1_api.register(MapLayerResource())
v1_api.register(MapResource())
v1_api.register(TimelineItemResource())
v1_api.register(UserResource())
v1_api.register(EventTypesResource())

urlpatterns = patterns(
    '',
    url(r'^/?', include('geoevents.operations.urls')),
    url(r'^/?$', RedirectView.as_view(url=reverse_lazy('active-incidents')), name='home'),
    url(r'^service-type/(?P<name>[\w]+)/$', 'geoevents.operations.views.service_type', name='view-service-type'),
    url(r'^service-types/$', 'geoevents.operations.views.service_types', name='view-service-types'),
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/login/$', 'django.contrib.auth.views.login', name='login'),
    url(r'^accounts/logout/$', 'geoevents.views.logout', name='logout'),
    url(r'^users/(?P<username>[\w\d\.@+-_\'\s]+)/$', UserPermsUpdate.as_view(), name='user-profile'),
    url(r'^api/', include(v1_api.urls), name='api-root'),
    url(r'^notes/', include('geoevents.notes.urls')),
    url(r'^services/$', 'geoevents.operations.views.view_services', name='operations-view-services'),
    url(r'^feedback/', include('geoevents.feedback.urls')),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^timeline/', include('geoevents.timeline.urls')),
    url(r'^director/', include('geoevents.director.urls')),
)

tinymce/urls.py
# Copyright (c) 2008 Joost Cassee
# Licensed under the terms of the MIT License (see LICENSE.txt)

from django.conf.urls.defaults import *

urlpatterns = patterns('tinymce.views',
    url(r'^js/textareas/(?P<name>.+)/$', 'textareas_js', name='tinymce-js'),
    url(r'^js/textareas/(?P<name>.+)/(?P<lang>.*)$', 'textareas_js', name='tinymce-js-lang'),
    url(r'^spellchecker/$', 'spell_check'),
    url(r'^flatpages_link_list/$', 'flatpages_link_list'),
    url(r'^compressor/$', 'compressor', name='tinymce-compressor'),
    url(r'^filebrowser/$', 'filebrowser', name='tinymce-filebrowser'),
    url(r'^preview/(?P<name>.+)/$', 'preview', name='tinymce-preview'),
)

geoevents/core/models.py
# This technical data was produced for the U. S. Government under Contract No. W15P7T-13-C-F600, and
# is subject to the Rights in Technical Data-Noncommercial Items clause at DFARS 252.227-7013 (FEB 2012)

import os
from datetime import datetime
from django.conf import settings
from django.contrib.gis.db import models


class Setting(models.Model):
    """
    Model for site-wide settings.
    """
    name = models.CharField(max_length=200, help_text="Name of site-wide variable")
    value = models.TextField(max_length=800, blank=True, help_text="Value of site-wide variable")

    def __unicode__(self):
        return self.name


class PageLinks(models.Model):
    """
    Model for Links to show title bars of pages.
    """
    name = models.CharField(max_length=50, help_text="Name of site-wide variable")
    category = models.CharField(max_length=100, blank=True, null=True,
                                help_text="Category on header bar that link should go under, will create a new one if needed")
    url = models.TextField(max_length=800, blank=True, null=True,
                           help_text="URL to page loaded in new tab. If a 'shortcut' is specified, add URL onto end of internal url (e.g. '?service=SuggestionBox')")
    shortcut = models.CharField(max_length=100, blank=True, null=True,
                                help_text="Internal shortcut to use instead of url (e.g. 'add-feedback')")
    show_for_types = models.CharField(max_length=100, blank=True, null=True,
                                      help_text="Leave blank to always show, or use 'incident' or 'dashboard' or something to only show in pages that have that in the url")

    def __unicode__(self):
        return self.name

geoevents/notes/models.py
# This technical data was produced for the U. S. Government under Contract No. W15P7T-13-C-F600, and
# is subject to the Rights in Technical Data-Noncommercial Items clause at DFARS 252.227-7013 (FEB 2012)

from django.db import models
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes import generic
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from tinymce.models import HTMLField
import json


class Note(models.Model):
    """ 
    This is the model for a Note. Notes have a required Title, Content, 
    and owner (which is a django.contrib.auth.models.User)

    """
    title = models.CharField(max_length=255)
    content = HTMLField(blank=True)
    public = models.BooleanField(default=True, help_text="Allow everyone to read this?", blank=True)
    owner = models.ForeignKey(User)
    created = models.DateTimeField(auto_now_add=True)
    last_updated = models.DateTimeField(auto_now=True)
    content_type = models.ForeignKey(ContentType)
    object_id = models.PositiveIntegerField()
    content_object = generic.GenericForeignKey('content_type', 'object_id')

    def __unicode__(self):
        return u'[{0}] {1}'.format(self.owner.username, self.title)

    class Meta:
        ordering = ['-last_updated', ]

    def get_absolute_url(self):
        return reverse('notes-view-note', args=[self.id])

    def note_info(self):
        return {
            "id": self.id,
            "title": self.title,
            "url": str(self.get_absolute_url()),
            "edit_url": str(self.get_edit_url()),
            "delete_url": str(self.get_delete_url()),
            "content": self.content,
            "posted_date": str(self.last_updated),
            "posted_by": str(self.owner),
        }

    def note_json(self):
        return json.dumps(self.note_info(), skipkeys=True, default={})

    def get_edit_url(self):
        return reverse('notes-manage-note-id', args=[self.id])

    def get_delete_url(self):
        return reverse('notes-delete-note-id', args=[self.id])

geoevents/director/forms.py
# This technical data was produced for the U. S. Government under Contract No. W15P7T-13-C-F600, and
# is subject to the Rights in Technical Data-Noncommercial Items clause at DFARS 252.227-7013 (FEB 2012)

from django.forms import ModelForm
from .models import Report, Actions, Billet


class ReportForm(ModelForm):
    class Meta:
        model = Report
        exclude = ('owner', 'rating_count')


class ReportFormMinimal(ModelForm):
    class Meta:
        model = Report
        exclude = ('owner', 'content_type', 'object_id')


class ActionForm(ModelForm):
    class Meta:
        model = Actions
        exclude = ('owner', 'rating_count')


class BilletForm(ModelForm):
    class Meta:
        model = Billet

geoevents/director/templates/director-dashboard-detail.html
{% extends "./base.html"%}

{% block title %}: {{ item.name }}{% endblock %}

{% load markup %}
{% load url from future %}

{% block css %}
<link href="{{STATIC_URL}}css/incident.css" rel="stylesheet" xmlns="http://www.w3.org/1999/html"/>
<link href="{{STATIC_URL}}css/widgets.css" rel="stylesheet" xmlns="http://www.w3.org/1999/html"/>
<link href="{{STATIC_URL}}timeline/timeline.css" rel="stylesheet">
<link href="{{STATIC_URL}}jquery-ui/cupertino/jquery-ui.min.css" rel="stylesheet"/>
<link href="{{STATIC_URL}}fullcalendar/fullcalendar.css" rel="stylesheet">
<link href="{{STATIC_URL}}fullcalendar/fullcalendar.print.css" rel="stylesheet">
<link href="{{STATIC_URL}}datatables.net/css/demo_page.css" rel="stylesheet" />
<link href="{{STATIC_URL}}datatables.net/css/demo_table.css" rel="stylesheet" />
<link href="{{STATIC_URL}}datatables.net/css/dataTables.TableTools.css" rel="stylesheet" />
{% endblock %}

{% block javascript %}
<script type="text/javascript" src="{{STATIC_URL}}timeline/timeline.js"></script>
<script type="text/javascript" src="{{STATIC_URL}}fullcalendar/fullcalendar.min.js"></script>
<script type="text/javascript" src="{{STATIC_URL}}js/jquery.cookie.js"></script>
<script type="text/javascript" src="{{STATIC_URL}}js/jquery.ba-bbq.min.js"></script>
<script type="text/javascript" src="{{STATIC_URL}}js/jquery.event.drag-2.2.js"></script>
<script type="text/javascript" src="{{STATIC_URL}}js/jquery.event.drop-2.2.js"></script>
<script type="text/javascript" src="{{STATIC_URL}}datatables.net/js/jquery.dataTables.js"></script>
<script type="text/javascript" src="{{STATIC_URL}}datatables.net/js/dataTables.TableTools.js"></script>
<script type="text/javascript" src="{{STATIC_URL}}datatables.net/js/dataTables.ZeroClipboard.js"></script>

<script type="text/javascript" src="{{STATIC_URL}}js/dashboard-support.js"></script>
<script type="text/javascript" src="{{STATIC_URL}}js/director-support.js"></script>
<script type="text/javascript" src="{{STATIC_URL}}js/director-support.drawwidgets.js"></script>
<script type="text/javascript" src="{{STATIC_URL}}js/director-support.plugins.timeline.js"></script>
<script type="text/javascript" src="{{STATIC_URL}}js/director-support.plugins.tables.js"></script>
<script type="text/javascript" src="{{STATIC_URL}}js/director-support.plugins.topprograms.js"></script>
<script type="text/javascript" src="{{STATIC_URL}}js/director-support.plugins.links.js"></script>
<script type="text/javascript" src="{{STATIC_URL}}js/director-support.plugins.calendar.js"></script>
<script type="text/javascript" src="{{STATIC_URL}}js/director-support.plugins.livingwar.js"></script>
<script type="text/javascript" src="{{STATIC_URL}}js/director-support.plugins.billet.js"></script>
<script type="text/javascript" src="{{STATIC_URL}}js/director-support.plugins.actions.js"></script>
<script type="text/javascript" src="{{STATIC_URL}}js/settings-manager.js"></script>

{% endblock %}
{% block javascript_no_compress %}

<script type="text/javascript">
var settings = {};
var dashboard = {};

$(document).ready(function() {
    director_support.init();

    dashboard.id = {{ item.id }};
    dashboard.org = '{{item.org}}';
    dashboard.name = '{{item.name}}';
    dashboard.owner = '{{item.owner}}';
    dashboard.site_icon = '{{item.site_icon}}';
    dashboard.status = '{{item.status}}';
    dashboard.type = '{{item.type}}';
    dashboard.tracking_code = '{{item.tracking_code}}';
    dashboard.current_user = '{{request.user.username}}';

    //Load list of page widgets and their configuration details
    dashboard.dates = {{item.dashboard_dates_json|safe}};

    dashboard.widgets = {{item.related_widget_list_json|safe}};
    director_support.parseNotesAndJSON(dashboard.widgets);

    //data is where widget-specific data will be kept
    dashboard.data={};

    //Timeline events will be populated by other widgets
    dashboard.data.timeline_events = [];

    event_pages.options.staticRoot = '{{STATIC_URL}}';
    event_pages.options.root = '{% url "home" %}';
    event_pages.options.csrf = "{% csrf_token %}";

    settings = {{settings|safe}};
    settings = event_pages.turnSettingsIntoObject(settings);

    if (dashboard.tracking_code){
        settings.owa_siteid = dashboard.tracking_code;
    }

    director_support.updateTitle(dashboard.org+" Executive Dashboard");

    //TODO: Make this an auto-grabbing, auto-updating data source, possibly AngularJS?
    dashboard.data.programs = {{item.related_programs_list_by_group_json|safe}};
    dashboard.data.links = {{item.related_links_list_json|safe}};
    dashboard.data.reports = {{item.reports_json|safe}};
    dashboard.data.reports_user = {{user_reports|safe}};
    dashboard.data.billets = {{item.billet_json|safe}};
    dashboard.data.actions = {{item.get_action_items|safe}};

    dashboard.permissions = {};
    dashboard.permissions.add_notes = ("{{ perms.notes.add_note }}"=="True");
    dashboard.permissions.edit_notes = ("{{ perms.notes.change_note }}"=="True");
    dashboard.permissions.add_report = ("{{ perms.director.add_report }}"=="True");
    dashboard.permissions.edit_report = ("{{ perms.director.change_report }}"=="True");
    dashboard.permissions.add_billet = ("{{ perms.director.add_billet }}"=="True");
    dashboard.permissions.edit_billet = ("{{ perms.director.change_billet }}"=="True");
    dashboard.permissions.delete_billet = ("{{ perms.director.delete_billet }}"=="True");
    dashboard.permissions.add_action = ("{{ perms.director.add_actions }}"=="True");
    dashboard.permissions.edit_action = ("{{ perms.director.change_actions }}"=="True");


    director_support.drawWidgets(dashboard);

//    $(".main-content").css('width','1200px');
});

</script>
{% endblock %}


{% block main-content %}
<!--Beginning of Left column-->
<div class="span12">

    <!--Header-->
    <div class="row-fluid">
        <div class="header">
            <!--<div class="page-header"><h2>{{item.org}} : {{item.name}}</h2></div>-->
            <div class="header-subtext">
                <div class="main title nav-header">Created: {{ item.created }}</div>
                <div class="sub-items"><span class="nav-header title">TAGS:</span>{% if item.tags_as_list %}{%for tag in item.tags_as_list%} <span class="label label-info">{{tag}}</span> {%endfor%} {%else%} No Tags {%endif%}
                </div>
            </div>
        </div>
    </div>

</div><!-- End of bottom column -->

{% endblock %}

geoevents/director/templates/director-dashboard-list.html
{% extends "./base.html" %}
{% block title %}: Director Dashboards{% endblock %}
{% load url from future  %}

{% block css %}
<link href="{{STATIC_URL}}css/events-list-dashboard.css" rel="stylesheet" xmlns="http://www.w3.org/1999/html"/>
<link href="{{STATIC_URL}}timeline/timeline.css" rel="stylesheet">
<style>
     div.olControlAttribution {
         bottom: 5px;
         color: #f2cf31;
         font-weight: bold;
     }
</style>
{% endblock %}


{% block javascript%}
<script type="text/javascript" src="{{STATIC_URL}}timeline/timeline.js"></script>
<script type="text/javascript" src="{{STATIC_URL}}js/jquery.cookie.js"></script>
<script type="text/javascript" src="{{STATIC_URL}}js/jquery.ba-bbq.min.js"></script>

<script type="text/javascript" src="{{STATIC_URL}}js/dashboard-support.js"></script>
<script type="text/javascript" src="{{STATIC_URL}}js/settings-manager.js"></script>
<script type="text/javascript">

$(document).ready(function() {
    var settings = {};

    //TODO: Need a better way to manage layer css within IE
    if ($ && $.browser && $.browser.msie){
        $('.span12').css('margin-left','0px');
        $('.span9').css('margin-left','0px');
    }

    event_pages.options.staticRoot = '{{STATIC_URL}}';
    event_pages.options.root = '{% url "home" %}';

    settings = {{settings|safe}};
    settings = event_pages.turnSettingsIntoObject(settings);

    $(".brand").text("Executive Dashboards");

});

</script>
{% endblock %}


{% block content %}
<div class="span12">

    <!--Header-->
    <div class="row-fluid">
        <div class="header">
            <div class="page-header"><h1>{{items|length}} Active Dashboard{{items|pluralize}}</h1></div>
        </div>
    </div>

    <div class="row-fluid">
        <table class="table table-hover">
            <thead>
            <tr>
                <th>Org</th>
                <th>Dashboard Name</th>
                <th>Date Added</th>
                <th>Status</th>
                <th>Owner</th>
            </tr>
            </thead>
            <tbody>
            {% for item in items %}
            <tr>
                <td><a href="{{item.get_absolute_url}}">{{item.org}}</a></td>
                <td><a href="{{item.get_absolute_url}}">{{item.name}}</a></td>
                <td>{{item.created}}</td>
                <td>{{item.status}}</td>
                <td>{{item.owner}}</td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>


</div><!-- End of bottom column -->



{% endblock %}

geoevents/director/templates/report-delete.html
 {% extends "./base.html" %}
 
 {%block javascript%}
<script type="text/javascript">
 </script>
 {%endblock%}
 
 {%block main-content%}
  <h2>Record #{{id}} has been deleted.</h2>


{%endblock%}

geoevents/director/templates/report-list.html
 {% extends "./base.html" %}
 {% load markup %}
 {% load url from future %}

 {%block javascript%}
<script type="text/javascript">
	function init(){
	$('.service_type').tooltip();
}</script>
 {%endblock%}
 
 {%block main-content%}
  <div class="page-header"><h1>{{reports_list|length}} Report{{reports_list|pluralize}}</h1></div>
  <a href="{% url 'reports-manage-report' %}" class="btn btn-mini btn-success"><i class="icon-plus icon-white"></i> Add New Report</a><br/><br/>
              <table class="table table-hover">
              <tbody>
			  <thead>
                <tr>
                  <th>Title</th>
                  <th>Date Added</th>
                  <th>Content</th>
                  <th></th>
                </tr>
              </thead>
              {% for report in reports_list%}
                <tr>
                   <td><a href="{{report.get_absolute_url}}">{{report.title}}</a></td>
				   <td>{{report.created}}</td>
					<td>{{report.details|truncatechars:70|markdown}}</td>
					<td><a href="{% url 'reports-manage-report-id' report.id %}" class="btn btn-small btn-primary"><i class="icon-pencil icon-white"></i> Edit</a>  <a href="{% url 'reports-delete-report-id' report.id %}" class="btn btn-small btn-danger"><i class="icon-trash icon-white"></i> Delete</a></td>
                </tr>
               {%endfor%} 
              </tbody>
      </table>
 
{% include "generic_paginator.html" %}
 
 {%endblock%}

geoevents/director/templates/report-manage.html
{% extends "base.html" %}

 {%block main-content%}
  <style>
    select, textarea, input[type="text"], input[type="password"], input[type="datetime"], input[type="datetime-local"], input[type="date"], input[type="month"], input[type="time"], input[type="week"], input[type="number"], input[type="email"], input[type="url"], input[type="search"], input[type="tel"], input[type="color"]{
        margin-bottom: 0;
    }
    .errorlist {
        margin-top: 8px;
        margin-bottom: 0px;
        background-color: red;
        color: black;
        width: 400px;
        border-radius: 4px;
        padding: 4px;
        margin-left: 0px;
    }
    .helptext {
        font-style: italic;
        font-size: .8em;
    }
  </style>
  <script>
      var reportForm = {};
      reportForm.init = function() {
          var urlPieces = _.str.rtrim(document.location.pathname,"/").split("/");
          urlPieces = urlPieces[urlPieces.length-1];
          var boardNum = parseInt(urlPieces);

          if (boardNum) {
              $("#id_owning_organization").val(boardNum);
          }

          var dtg = moment();
          dtg = dtg.format("YYYY-MM-DD HH:mm:ss"); //2014-02-14 05:00:00+00:00
          $("#id_date_assigned").val(dtg);

          var user_id = '{{ request.user.id }}';
          if (user_id){
              var $user = $("#id_originator");
              $user.val(user_id);
          }

          var category = _.str.ltrim(document.location.hash,"#");
          if (category) {
              $("#id_category").val(category);
          }
      };

      $(document).ready( reportForm.init );

  </script>

  <div class="page-header"><h1>{{form.title.value|default_if_none:"Add a Report"}} <small>{{item.last_updated}}</small></h1></div>
  <form method="post" action="">{% csrf_token %}

<table>
  {{form}}
</table>
<br/><br/><input type="submit" value="Save" data-role="button" class="btn btn-default btn-small" /> {%if form.pk%}<a href="{{delete_url}}" class="btn btn-small btn-danger"><i class="icon-trash icon-white"></i> Delete</a>{%endif%}
</form> 

{%endblock%}

geoevents/director/templates/report.html
 {% extends "./base.html" %}
 {% load url from future %}

 {%block main-content%}
  <div class="page-header"><h1>{{report.title}} <small>{{note.last_updated}}</small></h1></div>
              <tbody>
				 
 {% load markup %}
                <tr>
                  <td> <b>Title: </b>{{report.title}}<br/>
                  <b>Posted By:</b> {{report.owner}}<br/>
                  <b>Tags:</b> {{report.tags}}<br/>
                  <b>Date Created:</b> {{note.created}}<br/>
                  <b>Last Updated:</b> {{note.last_updated}}<br/><br/>
                  <div class="well">{{note.details|markdown}}</div></td>
                </tr>
              </tbody>
      </table>

     {%if perms.report.change_report%}<a href="{% url 'reports-manage-report-id' report.id %}" class="btn btn-primary"><i class="icon-pencil icon-white"></i> Edit</a>{% endif %} {%if perms.report.delete_report%}<a href="{% url 'reports-delete-report-id' report.id %}" class="btn btn-danger"><i class="icon-trash icon-white"></i> Delete</a>{% endif %}
 {%endblock%}